### ISSUE TITLE
the performance of eco is not good enough

### ISSUE THREAD

**Issue by XchenJH** [rockkingjy/Trackers_cpp#1]
the performance of your eco tracker is lower than origin eco by matlab, why?.....

**Comment by rockkingjy** [comment]
Yes, you're right, as said in the readme.md, it's still in developing now, not finished yet. But it will be done in recently.

**Comment by XchenJH** [comment]
@rockkingjy Thank you for your reply ! I appreciate your work very much . Do you know the code of SiamFC by c++? I found in the actual project that this tracking algorithm works well .

**Comment by rockkingjy** [comment]
@XchenJH Sorry, I don't have it yet. Maybe in the near future, I will add it to this repository.
